<?php

declare(strict_types=1);

/**
 * Plugin Name: Bleeding Deacons Shared Logger
 * Description: PSR-3 cross-plugin logging framework. Deployed automatically by Sentinel.
 * Version: 1.0.0
 * Author: The Bleeding Deacons
 * License: MIT
 *
 * This file is designed to live in mu-plugins/ where it auto-loads before
 * every regular plugin, making wp_log() universally available.
 *
 * DO NOT EDIT THIS FILE DIRECTLY — it is managed by the Sentinel plugin.
 * Changes will be overwritten on the next Sentinel activation or update.
 */

if (!defined('ABSPATH')) {
    exit;
}

// Guard: if the logger is already loaded (e.g. another copy), bail out.
if (function_exists('wp_log')) {
    return;
}

// ─── PSR-3 Log Levels (RFC 5424) ────────────────────────────────────────────

final class BD_Log_Level
{
    public const EMERGENCY = 'emergency';
    public const ALERT     = 'alert';
    public const CRITICAL  = 'critical';
    public const ERROR     = 'error';
    public const WARNING   = 'warning';
    public const NOTICE    = 'notice';
    public const INFO      = 'info';
    public const DEBUG     = 'debug';

    public const PRIORITY = [
        self::EMERGENCY => 0,
        self::ALERT     => 1,
        self::CRITICAL  => 2,
        self::ERROR     => 3,
        self::WARNING   => 4,
        self::NOTICE    => 5,
        self::INFO      => 6,
        self::DEBUG     => 7,
    ];

    public static function meetsThreshold(string $level, string $threshold): bool
    {
        return (self::PRIORITY[$level] ?? 7) <= (self::PRIORITY[$threshold] ?? 7);
    }
}

// ─── Channel: a named logger bound to a plugin / subsystem ──────────────────

final class BD_Log_Channel
{
    private string $channel;
    private BD_Shared_Logger $logger;

    public function __construct(string $channel, BD_Shared_Logger $logger)
    {
        $this->channel = sanitize_key($channel);
        $this->logger  = $logger;
    }

    public function emergency(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::EMERGENCY, $message, $context);
    }

    public function alert(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::ALERT, $message, $context);
    }

    public function critical(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::CRITICAL, $message, $context);
    }

    public function error(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::ERROR, $message, $context);
    }

    public function warning(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::WARNING, $message, $context);
    }

    public function notice(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::NOTICE, $message, $context);
    }

    public function info(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::INFO, $message, $context);
    }

    public function debug(string $message, array $context = []): void
    {
        $this->log(BD_Log_Level::DEBUG, $message, $context);
    }

    public function log(string $level, string $message, array $context = []): void
    {
        $context['_channel'] = $this->channel;
        $this->logger->dispatch($level, $message, $context);
    }

    public function getChannel(): string
    {
        return $this->channel;
    }
}

// ─── Core Logger Engine ─────────────────────────────────────────────────────

final class BD_Shared_Logger
{
    private static ?self $instance = null;

    /** @var BD_Log_Channel[] */
    private array $channels = [];

    private string $logDir;
    private string $logFile;
    private string $minLevel;
    private int    $maxFileSize;
    private int    $maxFiles;
    private bool   $enabled;

    private function __construct()
    {
        $this->logDir      = $this->resolveLogDir();
        $this->logFile     = $this->logDir . '/bd-shared.log';
        $this->minLevel    = $this->resolveConfig('BD_LOG_LEVEL', 'bd_logger_level', 'debug');
        $this->maxFileSize = (int) $this->resolveConfig('BD_LOG_MAX_SIZE', 'bd_logger_max_size', 5 * 1024 * 1024);
        $this->maxFiles    = (int) $this->resolveConfig('BD_LOG_MAX_FILES', 'bd_logger_max_files', 5);
        $this->enabled     = (bool) $this->resolveConfig('BD_LOG_ENABLED', 'bd_logger_enabled', true);

        $this->ensureLogDir();

        register_shutdown_function([$this, 'handleShutdown']);
    }

    public static function instance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Get or create a named channel.
     *
     *   BD_Shared_Logger::channel('sentinel')->info('Widget loaded');
     */
    public static function channel(string $name): BD_Log_Channel
    {
        $logger = self::instance();
        $key    = sanitize_key($name);

        if (!isset($logger->channels[$key])) {
            $logger->channels[$key] = new BD_Log_Channel($key, $logger);
        }

        return $logger->channels[$key];
    }

    // ── Dispatch ──

    public function getLogFile(): string
    {
        return $this->logFile;
    }

    public function dispatch(string $level, string $message, array $context): void
    {
        if (!$this->enabled) {
            return;
        }

        if (!BD_Log_Level::meetsThreshold($level, $this->minLevel)) {
            return;
        }

        $message = $this->interpolate($message, $context);

        /**
         * Filter: modify or suppress a log entry.
         * Return null to suppress entirely.
         *
         * @param array|null $entry   { level, message, context }
         * @param string     $channel
         */
        $entry = apply_filters('bd_logger_entry', [
            'level'   => $level,
            'message' => $message,
            'context' => $context,
        ], $context['_channel'] ?? 'default');

        if ($entry === null) {
            return;
        }

        $line = $this->format($entry['level'], $entry['message'], $entry['context']);
        $this->write($line);

        /**
         * Action: fired after a log entry is written.
         * Hook into this to forward logs to Sentry, Datadog, Slack, etc.
         */
        do_action('bd_logger_after_write', $entry['level'], $entry['message'], $entry['context']);
    }

    // ── Formatting ──

    private function format(string $level, string $message, array $context): string
    {
        $channel = $context['_channel'] ?? 'default';
        unset($context['_channel']);

        $context = $this->redact($context);

        $ctx = !empty($context)
            ? ' ' . wp_json_encode($context, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
            : '';

        return sprintf(
            "[%s] [%s] [%s] [%s] [req:%s] [mem:%s] %s%s\n",
            gmdate('Y-m-d\TH:i:s\Z'),
            strtoupper($level),
            $channel,
            $this->getRequestType(),
            $this->getRequestId(),
            size_format(memory_get_usage(true)),
            $message,
            $ctx
        );
    }

    /**
     * PSR-3 placeholder interpolation.
     *   "Order {order_id} placed" + ['order_id' => 42] → "Order 42 placed"
     */
    private function interpolate(string $message, array $context): string
    {
        $replace = [];
        foreach ($context as $key => $val) {
            if (is_string($key) && $key[0] !== '_' && (is_scalar($val) || $val instanceof \Stringable)) {
                $replace['{' . $key . '}'] = (string) $val;
            }
        }
        return strtr($message, $replace);
    }

    /**
     * Scrub known-sensitive keys from context before writing.
     */
    private function redact(array $context): array
    {
        static $sensitive = [
            'password', 'passwd', 'secret', 'token', 'api_key',
            'apikey', 'access_token', 'refresh_token', 'credit_card',
            'card_number', 'cvv', 'ssn', 'authorization',
        ];

        foreach ($context as $key => &$value) {
            if (in_array(strtolower($key), $sensitive, true)) {
                $value = '*** REDACTED ***';
            } elseif (is_array($value)) {
                $value = $this->redact($value);
            }
        }
        unset($value);

        return $context;
    }

    // ── Writing & Rotation ──

    private function write(string $line): void
    {
        $this->maybeRotate();

        $written = @file_put_contents($this->logFile, $line, FILE_APPEND | LOCK_EX);

        if ($written === false) {
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
            error_log('[BD_Shared_Logger] ' . trim($line));
        }
    }

    private function maybeRotate(): void
    {
        if (!file_exists($this->logFile)) {
            return;
        }

        $size = @filesize($this->logFile);
        if ($size === false || $size < $this->maxFileSize) {
            return;
        }

        for ($i = $this->maxFiles - 1; $i >= 1; $i--) {
            $src = $this->logFile . '.' . $i;
            $dst = $this->logFile . '.' . ($i + 1);
            if (file_exists($src)) {
                @rename($src, $dst);
            }
        }

        @rename($this->logFile, $this->logFile . '.1');

        $oldest = $this->logFile . '.' . ($this->maxFiles + 1);
        if (file_exists($oldest)) {
            @unlink($oldest);
        }
    }

    // ── Directory & Security ──

    private function resolveLogDir(): string
    {
        if (defined('BD_LOG_DIR')) {
            return untrailingslashit(BD_LOG_DIR);
        }
        return untrailingslashit(WP_CONTENT_DIR) . '/logs';
    }

    private function ensureLogDir(): void
    {
        if (!file_exists($this->logDir)) {
            wp_mkdir_p($this->logDir);
        }

        $htaccess = $this->logDir . '/.htaccess';
        if (!file_exists($htaccess)) {
            @file_put_contents($htaccess, "Deny from all\n");
        }

        $index = $this->logDir . '/index.php';
        if (!file_exists($index)) {
            @file_put_contents($index, "<?php // Silence is golden.\n");
        }
    }

    // ── Request Context ──

    private function getRequestType(): string
    {
        if (defined('WP_CLI') && WP_CLI) {
            return 'CLI';
        }
        if (function_exists('wp_doing_cron') && wp_doing_cron()) {
            return 'CRON';
        }
        if (function_exists('wp_doing_ajax') && wp_doing_ajax()) {
            return 'AJAX';
        }
        if (defined('REST_REQUEST') && REST_REQUEST) {
            return 'REST';
        }
        return function_exists('is_admin') && is_admin() ? 'ADMIN' : 'FRONT';
    }

    private function getRequestId(): string
    {
        static $id = null;
        if ($id === null) {
            $id = substr(bin2hex(random_bytes(4)), 0, 8);
        }
        return $id;
    }

    // ── Configuration Resolution ──

    /**
     * Resolve config: constant → filter → default.
     */
    private function resolveConfig(string $constant, string $filter, mixed $default): mixed
    {
        if (defined($constant)) {
            return constant($constant);
        }
        return apply_filters($filter, $default);
    }

    // ── Fatal Error Capture ──

    public function handleShutdown(): void
    {
        $error = error_get_last();
        if ($error === null) {
            return;
        }

        $fatalTypes = [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR];
        if (!in_array($error['type'], $fatalTypes, true)) {
            return;
        }

        $context = [
            '_channel' => 'php',
            'file'     => $error['file'],
            'line'     => $error['line'],
            'type'     => $error['type'],
        ];

        $line = $this->format('emergency', 'Fatal: ' . $error['message'], $context);
        @file_put_contents($this->logFile, $line, FILE_APPEND | LOCK_EX);
    }

    // ── WP-CLI ──

    public static function registerCli(): void
    {
        // Kept for backwards compat — actual registration is now via BD_Shared_Logger_CLI class
    }
}

// ─── WP-CLI Command Class ───────────────────────────────────────────────────

/**
 * Manage the shared log file.
 */
class BD_Shared_Logger_CLI extends \WP_CLI_Command
{
    /**
     * Show the last N lines of the log file.
     *
     * ## OPTIONS
     *
     * [--lines=<number>]
     * : Number of lines to show. Default: 50
     *
     * [--channel=<name>]
     * : Filter to a specific plugin channel.
     *
     * [--level=<level>]
     * : Filter to a specific log level (debug, info, warning, error, critical).
     *
     * ## EXAMPLES
     *
     *     wp log tail
     *     wp log tail --lines=100
     *     wp log tail --channel=amber
     *     wp log tail --channel=reconcile --level=error
     *
     */
    public function tail($args, $assoc_args): void
    {
        $logger  = BD_Shared_Logger::instance();
        $lines   = (int) ($assoc_args['lines'] ?? 50);
        $channel = $assoc_args['channel'] ?? null;
        $level   = $assoc_args['level'] ?? null;
        $file    = $logger->getLogFile();

        if (!file_exists($file)) {
            \WP_CLI::error('Log file not found: ' . $file);
        }

        $output = [];
        $fp = fopen($file, 'r');
        if ($fp) {
            $allLines = [];
            while (($line = fgets($fp)) !== false) {
                $line = rtrim($line);
                if (empty($line)) {
                    continue;
                }
                if ($channel && !str_contains($line, "[$channel]")) {
                    continue;
                }
                if ($level && !str_contains($line, '[' . strtoupper($level) . ']')) {
                    continue;
                }
                $allLines[] = $line;
            }
            fclose($fp);
            $output = array_slice($allLines, -$lines);
        }

        if (empty($output)) {
            \WP_CLI::log('(no matching log entries)');
            return;
        }

        foreach ($output as $line) {
            \WP_CLI::log($line);
        }
    }

    /**
     * Clear the log file.
     *
     * ## EXAMPLES
     *
     *     wp log clear
     *
     */
    public function clear($args, $assoc_args): void
    {
        $logger = BD_Shared_Logger::instance();
        $file   = $logger->getLogFile();

        if (file_exists($file)) {
            file_put_contents($file, '');
            \WP_CLI::success('Log file cleared.');
        } else {
            \WP_CLI::warning('No log file found.');
        }
    }

    /**
     * Show the log file path.
     *
     * ## EXAMPLES
     *
     *     wp log path
     *
     */
    public function path($args, $assoc_args): void
    {
        $logger = BD_Shared_Logger::instance();
        \WP_CLI::log($logger->getLogFile());
    }
}

// ── Bootstrap ───────────────────────────────────────────────────────────────

// WP-CLI commands are registered by Sentinel.php (the parent plugin),
// not here, because mu-plugin CLI registration is unreliable across
// different WP-CLI versions and hosting environments.

// ── Global Helper ───────────────────────────────────────────────────────────

/**
 * Get a named log channel.
 *
 *   wp_log('sentinel')->info('Widget loaded');
 *   wp_log('unity')->error('Sync failed', ['reason' => $e->getMessage()]);
 */
function wp_log(string $channel = 'default'): BD_Log_Channel
{
    return BD_Shared_Logger::channel($channel);
}
