<?php

declare(strict_types=1);

/**
 * Plugin Name: Sentinel Shared Logger
 * Description: PSR-3 cross-plugin logging framework. Deployed automatically by Sentinel.
 * Version: 2.1.8
 * Author: The Bleeding Deacons
 * License: MIT
 *
 * This file is designed to live in mu-plugins/ where it auto-loads before
 * every regular plugin, making wp_log() universally available.
 *
 * DO NOT EDIT THIS FILE DIRECTLY — it is managed by the Sentinel plugin.
 * Changes will be overwritten on the next Sentinel activation or update.
 */

if (!defined('ABSPATH')) {
    exit;
}

// Guard: if the logger is already loaded (e.g. another copy), bail out.
if (function_exists('wp_log')) {
    return;
}

// ─── PSR-3 Log Levels (RFC 5424) ────────────────────────────────────────────

final class Sentinel_Log_Level
{
    public const EMERGENCY = 'emergency';
    public const ALERT     = 'alert';
    public const CRITICAL  = 'critical';
    public const ERROR     = 'error';
    public const WARNING   = 'warning';
    public const NOTICE    = 'notice';
    public const INFO      = 'info';
    public const DEBUG     = 'debug';

    public const PRIORITY = [
        self::EMERGENCY => 0,
        self::ALERT     => 1,
        self::CRITICAL  => 2,
        self::ERROR     => 3,
        self::WARNING   => 4,
        self::NOTICE    => 5,
        self::INFO      => 6,
        self::DEBUG     => 7,
    ];

    public static function meetsThreshold(string $level, string $threshold): bool
    {
        return (self::PRIORITY[$level] ?? 7) <= (self::PRIORITY[$threshold] ?? 7);
    }
}

// ─── Channel: a named logger bound to a plugin / subsystem ──────────────────

final class Sentinel_Log_Channel
{
    private string $channel;
    private Sentinel_Logger $logger;

    public function __construct(string $channel, Sentinel_Logger $logger)
    {
        $this->channel = sanitize_key($channel);
        $this->logger  = $logger;
    }

    public function emergency(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::EMERGENCY, $message, $context);
    }

    public function alert(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::ALERT, $message, $context);
    }

    public function critical(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::CRITICAL, $message, $context);
    }

    public function error(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::ERROR, $message, $context);
    }

    public function warning(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::WARNING, $message, $context);
    }

    public function notice(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::NOTICE, $message, $context);
    }

    public function info(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::INFO, $message, $context);
    }

    public function debug(string $message, array $context = []): void
    {
        $this->log(Sentinel_Log_Level::DEBUG, $message, $context);
    }

    public function log(string $level, string $message, array $context = []): void
    {
        $context['_channel'] = $this->channel;
        $this->logger->dispatch($level, $message, $context);
    }

    public function getChannel(): string
    {
        return $this->channel;
    }
}

// ─── Core Logger Engine ─────────────────────────────────────────────────────

final class Sentinel_Logger
{
    private static ?self $instance = null;

    /**
     * Database table name (without prefix).
     */
    public const TABLE_NAME = 'sentinel_log_entries';

    /**
     * DB schema version — bump this when the table structure changes.
     */
    public const DB_VERSION = '2.1.0';

    /**
     * Option key that stores the installed schema version.
     */
    private const DB_VERSION_OPTION = 'sentinel_logger_db_version';

    /** @var Sentinel_Log_Channel[] */
    private array $channels = [];

    /**
     * In-memory write buffer.
     *
     * Entries accumulate here during the request and are flushed to the
     * database in a single bulk INSERT either when the buffer reaches
     * $bufferLimit, when flush() is called explicitly, or automatically
     * at shutdown.
     *
     * @var list<array{logged_at: string, level: string, channel: string, request_type: string, request_id: string, memory: string, message: string, context: string}>
     */
    private array $buffer = [];

    private string $minLevel;
    private int    $maxRows;
    private int    $bufferLimit;
    private bool   $enabled;

    private function __construct()
    {
        $this->minLevel    = $this->resolveConfig('SENTINEL_LOG_LEVEL', 'sentinel_logger_level', 'debug');
        $this->maxRows     = (int) $this->resolveConfig('SENTINEL_LOG_MAX_ROWS', 'sentinel_logger_max_rows', 10000);
        $this->bufferLimit = (int) $this->resolveConfig('SENTINEL_LOG_BUFFER_SIZE', 'sentinel_logger_buffer_size', 50);
        $this->enabled     = (bool) $this->resolveConfig('SENTINEL_LOG_ENABLED', 'sentinel_logger_enabled', true);

        $this->maybeCreateTable();

        // Auto-flush remaining buffer at the very end of the request.
        register_shutdown_function([$this, 'handleShutdown']);
    }

    public static function instance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Get or create a named channel.
     */
    public static function channel(string $name): Sentinel_Log_Channel
    {
        $logger = self::instance();
        $key    = sanitize_key($name);

        if (!isset($logger->channels[$key])) {
            $logger->channels[$key] = new Sentinel_Log_Channel($key, $logger);
        }

        return $logger->channels[$key];
    }

    /**
     * Get the full table name (with WP prefix).
     */
    public static function tableName(): string
    {
        global $wpdb;
        return $wpdb->prefix . self::TABLE_NAME;
    }

    // ── Buffer ──

    /**
     * Return the number of entries currently held in the buffer.
     */
    public function bufferCount(): int
    {
        return count($this->buffer);
    }

    /**
     * Flush the in-memory buffer to the database.
     *
     * Uses a single bulk INSERT for efficiency. Safe to call multiple
     * times — if the buffer is empty it's a no-op.
     *
     * @return int Number of rows written.
     */
    public function flush(): int
    {
        if (empty($this->buffer)) {
            return 0;
        }

        global $wpdb;
        $table = self::tableName();

        $columns = ['logged_at', 'level', 'channel', 'request_type', 'request_id', 'memory', 'message', 'context'];
        $placeholders = [];
        $values       = [];

        foreach ($this->buffer as $row) {
            $placeholders[] = '(%s, %s, %s, %s, %s, %s, %s, %s)';
            foreach ($columns as $col) {
                $values[] = $row[$col];
            }
        }

        $count = count($this->buffer);
        $this->buffer = [];

        $colList = implode(', ', $columns);
        $phList  = implode(', ', $placeholders);

        $escapedTable = '`' . esc_sql($table) . '`';

        // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table name from $wpdb->prefix; cannot be parameterised with prepare()
        $sql = $wpdb->prepare(
            "INSERT INTO {$escapedTable} ({$colList}) VALUES {$phList}",
            ...$values
        );

        // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
        $result = $wpdb->query($sql);

        if ($result === false) {
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
            error_log('[Sentinel_Logger] Bulk INSERT failed: ' . $wpdb->last_error);
            return 0;
        }

        $this->maybePrune();

        return $count;
    }

    // ── Table Management ──

    private function maybeCreateTable(): void
    {
        $installed = get_option(self::DB_VERSION_OPTION, '');

        if ($installed === self::DB_VERSION) {
            return;
        }

        $this->createTable();
        update_option(self::DB_VERSION_OPTION, self::DB_VERSION);
    }

    public static function createTable(): void
    {
        global $wpdb;
        $table   = self::tableName();
        $charset = $wpdb->get_charset_collate();

        $sql = "CREATE TABLE {$table} (
            id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
            logged_at datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
            level varchar(20) NOT NULL DEFAULT '',
            channel varchar(100) NOT NULL DEFAULT '',
            request_type varchar(10) NOT NULL DEFAULT '',
            request_id varchar(16) NOT NULL DEFAULT '',
            memory varchar(20) NOT NULL DEFAULT '',
            message text NOT NULL,
            context longtext NOT NULL,
            PRIMARY KEY  (id),
            KEY idx_level (level),
            KEY idx_channel (channel),
            KEY idx_logged_at (logged_at),
            KEY idx_channel_level (channel, level)
        ) $charset;";

        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        dbDelta($sql);
    }

    public static function dropTable(): void
    {
        global $wpdb;
        $table = self::tableName();
        // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table name from $wpdb->prefix; cannot be parameterised with prepare()
        $wpdb->query("DROP TABLE IF EXISTS `" . esc_sql($table) . "`");
        delete_option(self::DB_VERSION_OPTION);
    }

    public static function truncateTable(): void
    {
        global $wpdb;
        $table = self::tableName();
        // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table name from $wpdb->prefix; cannot be parameterised with prepare()
        $wpdb->query("TRUNCATE TABLE `" . esc_sql($table) . "`");
    }

    // ── Dispatch ──

    public function dispatch(string $level, string $message, array $context): void
    {
        if (!$this->enabled) {
            return;
        }

        if (!Sentinel_Log_Level::meetsThreshold($level, $this->minLevel)) {
            return;
        }

        $message = $this->interpolate($message, $context);

        /**
         * Filter: modify or suppress a log entry.
         * Return null to suppress entirely.
         */
        $entry = apply_filters('sentinel_logger_entry', [
            'level'   => $level,
            'message' => $message,
            'context' => $context,
        ], $context['_channel'] ?? 'default');

        if ($entry === null) {
            return;
        }

        $this->enqueue($entry['level'], $entry['message'], $entry['context']);

        /**
         * Action: fired after a log entry is buffered.
         */
        do_action('sentinel_logger_after_write', $entry['level'], $entry['message'], $entry['context']);
    }

    // ── Buffered Writing ──

    /**
     * Add a prepared row to the in-memory buffer.
     * Auto-flushes when the buffer reaches the configured limit.
     */
    private function enqueue(string $level, string $message, array $context): void
    {
        $channel = $context['_channel'] ?? 'default';
        unset($context['_channel']);
        $context = $this->redact($context);

        $contextJson = !empty($context)
            ? json_encode($context, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
            : '';

        $memory = memory_get_usage(true);
        $memoryStr = $memory < 1048576
            ? round($memory / 1024) . ' KB'
            : round($memory / 1048576, 1) . ' MB';

        $this->buffer[] = [
            'logged_at'    => gmdate('Y-m-d H:i:s'),
            'level'        => $level,
            'channel'      => $channel,
            'request_type' => $this->getRequestType(),
            'request_id'   => $this->getRequestId(),
            'memory'       => $memoryStr,
            'message'      => $message,
            'context'      => $contextJson ?: '',
        ];

        // Auto-flush when buffer is full.
        if (count($this->buffer) >= $this->bufferLimit) {
            $this->flush();
        }
    }

    /**
     * Remove oldest rows when the table exceeds the max row limit.
     */
    private function maybePrune(): void
    {
        // Only prune roughly 1 in 100 flushes to keep things fast.
        // Uses random_int() instead of wp_rand() — safe during shutdown
        // when WordPress functions may no longer be available.
        if (random_int(1, 100) !== 1) {
            return;
        }

        global $wpdb;
        $table = self::tableName();
        $escapedTable = '`' . esc_sql($table) . '`';

        // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table name from $wpdb->prefix; cannot be parameterised with prepare()
        $count = (int) $wpdb->get_var("SELECT COUNT(*) FROM {$escapedTable}");

        if ($count <= $this->maxRows) {
            return;
        }

        $excess = $count - $this->maxRows;

        // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- table name from $wpdb->prefix; cannot be parameterised with prepare()
        $wpdb->query($wpdb->prepare(
            "DELETE FROM {$escapedTable} ORDER BY id ASC LIMIT %d",
            $excess
        ));
    }

    // ── Interpolation & Redaction ──

    private function interpolate(string $message, array $context): string
    {
        $replace = [];
        foreach ($context as $key => $val) {
            if (is_string($key) && $key[0] !== '_' && (is_scalar($val) || $val instanceof \Stringable)) {
                $replace['{' . $key . '}'] = (string) $val;
            }
        }
        return strtr($message, $replace);
    }

    private function redact(array $context): array
    {
        static $sensitive = [
            'password', 'passwd', 'secret', 'token', 'api_key',
            'apikey', 'access_token', 'refresh_token', 'credit_card',
            'card_number', 'cvv', 'ssn', 'authorization',
        ];

        foreach ($context as $key => &$value) {
            if (is_string($key) && in_array(strtolower($key), $sensitive, true)) {
                $value = '*** REDACTED ***';
            } elseif (is_array($value)) {
                $value = $this->redact($value);
            }
        }
        unset($value);

        return $context;
    }

    // ── Request Context ──

    private function getRequestType(): string
    {
        if (defined('WP_CLI') && WP_CLI) {
            return 'CLI';
        }
        if (function_exists('wp_doing_cron') && wp_doing_cron()) {
            return 'CRON';
        }
        if (function_exists('wp_doing_ajax') && wp_doing_ajax()) {
            return 'AJAX';
        }
        if (defined('REST_REQUEST') && REST_REQUEST) {
            return 'REST';
        }
        return function_exists('is_admin') && is_admin() ? 'ADMIN' : 'FRONT';
    }

    private function getRequestId(): string
    {
        static $id = null;
        if ($id === null) {
            $id = substr(bin2hex(random_bytes(4)), 0, 8);
        }
        return $id;
    }

    // ── Configuration Resolution ──

    private function resolveConfig(string $constant, string $filter, mixed $default): mixed
    {
        if (defined($constant)) {
            return constant($constant);
        }
        return apply_filters($filter, $default);
    }

    // ── Shutdown Handler ──

    /**
     * Flush any remaining buffered entries and capture fatal errors.
     */
    public function handleShutdown(): void
    {
        // 1. Flush remaining buffer.
        $this->flush();

        // 2. Capture fatal errors.
        $error = error_get_last();
        if ($error === null) {
            return;
        }

        $fatalTypes = [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR];
        if (!in_array($error['type'], $fatalTypes, true)) {
            return;
        }

        global $wpdb;

        // Use json_encode() instead of wp_json_encode() — safe during shutdown.
        $context = json_encode([
            'file' => $error['file'],
            'line' => $error['line'],
            'type' => $error['type'],
        ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        // Use a plain byte count instead of size_format() — safe during shutdown.
        $memory = memory_get_usage(true);
        $memoryStr = $memory < 1048576
            ? round($memory / 1024) . ' KB'
            : round($memory / 1048576, 1) . ' MB';

        // Direct insert — buffer is already flushed, keep this immediate.
        $wpdb->insert(
            self::tableName(),
            [
                'logged_at'    => gmdate('Y-m-d H:i:s'),
                'level'        => 'emergency',
                'channel'      => 'php',
                'request_type' => $this->getRequestType(),
                'request_id'   => $this->getRequestId(),
                'memory'       => $memoryStr,
                'message'      => 'Fatal: ' . $error['message'],
                'context'      => $context ?: '',
            ],
            ['%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
        );
    }
}

// ── Global Helpers ──────────────────────────────────────────────────────────

/**
 * Get a named log channel.
 *
 *   wp_log('sentinel')->info('Widget loaded');
 *   wp_log('unity')->error('Sync failed', ['reason' => $e->getMessage()]);
 */
if ( ! function_exists( 'wp_log' ) ) {
    function wp_log(string $channel = 'default'): Sentinel_Log_Channel
    {
        return Sentinel_Logger::channel($channel);
    }
}

/**
 * Flush any buffered log entries to the database immediately.
 *
 *   wp_log_flush();
 *
 * @return int Number of rows written.
 */
if ( ! function_exists( 'wp_log_flush' ) ) {
    function wp_log_flush(): int
    {
        return Sentinel_Logger::instance()->flush();
    }
}

// ─── PHP Error, Exception, and wp_die Handlers ─────────────────────────────
//
// These handlers capture PHP warnings/notices/deprecation, uncaught exceptions,
// and wp_die() calls, logging them through the Sentinel channel system.
//
// Registered AFTER the logger classes and wp_log() are defined so that the
// logging API is guaranteed to be available when they fire.
//
// Each handler chains to the previously registered handler (if any) so that
// other plugins' error handlers (debugging tools, error trackers) are not
// displaced. The exception handler delegates to the previous handler after
// logging, preserving WordPress's own handling.
//
// Controlled by SENTINEL_CAPTURE_ERRORS (constant or filter):
//   - true  (default): Sentinel registers its error/exception/wp_die handlers
//   - false: Sentinel only provides the logger; no global handlers are installed
//
// To disable from wp-config.php:
//   define( 'SENTINEL_CAPTURE_ERRORS', false );
//
// To disable via filter (from a plugin):
//   add_filter( 'sentinel_capture_errors', '__return_false' );
//

$sentinel_capture_errors = defined('SENTINEL_CAPTURE_ERRORS')
    ? SENTINEL_CAPTURE_ERRORS
    : apply_filters('sentinel_capture_errors', true);

if ($sentinel_capture_errors) {

    // ── Error handler (warnings, notices, deprecation) ──────────────────
    //
    // Captures the previous handler and delegates to it after logging,
    // so debugging tools like Xdebug, Query Monitor, or other plugins
    // that register their own error handlers continue to work.

    $sentinel_previous_error_handler = set_error_handler(null);
    restore_error_handler();

    set_error_handler(function (int $errno, string $errstr, ?string $errfile = null, ?int $errline = null) use ($sentinel_previous_error_handler) {

        // Respect error suppression with @
        if (error_reporting() === 0) {
            return false;
        }

        // Map PHP error constants to PSR-3 levels
        static $map = [
            E_WARNING           => Sentinel_Log_Level::WARNING,
            E_USER_WARNING      => Sentinel_Log_Level::WARNING,
            E_NOTICE            => Sentinel_Log_Level::NOTICE,
            E_USER_NOTICE       => Sentinel_Log_Level::NOTICE,
            E_DEPRECATED        => Sentinel_Log_Level::NOTICE,
            E_USER_DEPRECATED   => Sentinel_Log_Level::NOTICE,
            E_STRICT            => Sentinel_Log_Level::NOTICE,
            E_USER_ERROR        => Sentinel_Log_Level::ERROR,
            E_RECOVERABLE_ERROR => Sentinel_Log_Level::ERROR,
        ];

        $level = $map[$errno] ?? Sentinel_Log_Level::ERROR;

        wp_log('php')->log(
            $level,
            $errstr,
            [
                'errno' => $errno,
                'file'  => $errfile,
                'line'  => $errline,
            ]
        );

        // Chain to the previous error handler if one was registered
        if ($sentinel_previous_error_handler !== null) {
            return $sentinel_previous_error_handler($errno, $errstr, $errfile, $errline);
        }

        // Let PHP continue default handling
        return false;
    });

    // ── Exception handler ───────────────────────────────────────────────
    //
    // Captures the previous handler and delegates to it after logging.
    // If no previous handler exists, the exception will terminate the
    // process (PHP's default behaviour for uncaught exceptions).

    $sentinel_previous_exception_handler = set_exception_handler(null);
    restore_exception_handler();

    set_exception_handler(function (Throwable $e) use ($sentinel_previous_exception_handler) {
        wp_log('php')->critical(
            'Uncaught exception: {message}',
            [
                'message' => $e->getMessage(),
                'file'    => $e->getFile(),
                'line'    => $e->getLine(),
                'trace'   => $e->getTraceAsString(),
            ]
        );

        // Flush immediately — the process may terminate after this
        wp_log_flush();

        // Chain to the previous exception handler
        if ($sentinel_previous_exception_handler !== null) {
            $sentinel_previous_exception_handler($e);
            return;
        }

        // No previous handler — PHP's default behaviour is to terminate,
        // which will happen naturally when this handler returns for an
        // uncaught exception (PHP 8.0+ re-throws internally).
    });

    // ── wp_die() handler ────────────────────────────────────────────────
    //
    // Uses a late-priority filter to wrap whatever handler is already
    // registered (whether WordPress's default or another plugin's),
    // rather than hardcoding _default_wp_die_handler. This ensures
    // wp_die handlers registered at normal priority are preserved.

    add_filter('wp_die_handler', function ($handler) {
        return function ($message, $title = '', $args = []) use ($handler) {

            wp_log('wp')->critical(
                'wp_die: {message}',
                [
                    'message' => is_string($message) ? wp_strip_all_tags($message) : json_encode($message),
                    'title'   => $title,
                    'args'    => $args,
                    'file'    => $args['file'] ?? null,
                    'line'    => $args['line'] ?? null,
                ]
            );

            // Flush immediately — wp_die typically terminates the process
            wp_log_flush();

            // Delegate to the previous handler (WordPress default or
            // another plugin's handler)
            if (is_callable($handler)) {
                return call_user_func($handler, $message, $title, $args);
            }

            // Fallback if the previous handler is not callable
            call_user_func('_default_wp_die_handler', $message, $title, $args);
        };
    }, 9999);
}